#############################################################################
# Makefile for building: qDB
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 13 11:23:02 2014
# Project:  progetto.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile progetto.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iprog -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = app.cpp \
		controller.cpp \
		form.cpp \
		hardware.cpp \
		prima.cpp \
		propsw.cpp \
		sharesw.cpp \
		software.cpp \
		ware.cpp \
		main.cpp \
		seconda.cpp \
		terza.cpp \
		showSearch.cpp moc_controller.cpp \
		moc_form.cpp \
		moc_seconda.cpp \
		moc_showSearch.cpp
OBJECTS       = app.o \
		controller.o \
		form.o \
		hardware.o \
		prima.o \
		propsw.o \
		sharesw.o \
		software.o \
		ware.o \
		main.o \
		seconda.o \
		terza.o \
		showSearch.o \
		moc_controller.o \
		moc_form.o \
		moc_seconda.o \
		moc_showSearch.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		progetto.pro
QMAKE_TARGET  = qDB
DESTDIR       = 
TARGET        = qDB

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: progetto.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile progetto.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile progetto.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qDB1.0.0 || $(MKDIR) .tmp/qDB1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qDB1.0.0/ && $(COPY_FILE) --parents app.h container.h controller.h form.h hardware.h prima.h propsw.h sharesw.h software.h ware.h seconda.h terza.h showSearch.h .tmp/qDB1.0.0/ && $(COPY_FILE) --parents app.cpp controller.cpp form.cpp hardware.cpp prima.cpp propsw.cpp sharesw.cpp software.cpp ware.cpp main.cpp seconda.cpp terza.cpp showSearch.cpp .tmp/qDB1.0.0/ && (cd `dirname .tmp/qDB1.0.0` && $(TAR) qDB1.0.0.tar qDB1.0.0 && $(COMPRESS) qDB1.0.0.tar) && $(MOVE) `dirname .tmp/qDB1.0.0`/qDB1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qDB1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_controller.cpp moc_form.cpp moc_seconda.cpp moc_showSearch.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_controller.cpp moc_form.cpp moc_seconda.cpp moc_showSearch.cpp
moc_controller.cpp: prima.h \
		seconda.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		form.h \
		controller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) controller.h -o moc_controller.cpp

moc_form.cpp: prima.h \
		form.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) form.h -o moc_form.cpp

moc_seconda.cpp: app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		seconda.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) seconda.h -o moc_seconda.cpp

moc_showSearch.cpp: terza.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		showSearch.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) showSearch.h -o moc_showSearch.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

app.o: app.cpp ware.h \
		app.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o app.o app.cpp

controller.o: controller.cpp controller.h \
		prima.h \
		seconda.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

form.o: form.cpp form.h \
		prima.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form.o form.cpp

hardware.o: hardware.cpp ware.h \
		hardware.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hardware.o hardware.cpp

prima.o: prima.cpp prima.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prima.o prima.cpp

propsw.o: propsw.cpp ware.h \
		software.h \
		propsw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propsw.o propsw.cpp

sharesw.o: sharesw.cpp ware.h \
		software.h \
		sharesw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sharesw.o sharesw.cpp

software.o: software.cpp ware.h \
		software.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o software.o software.cpp

ware.o: ware.cpp ware.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ware.o ware.cpp

main.o: main.cpp controller.h \
		prima.h \
		seconda.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

seconda.o: seconda.cpp seconda.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h \
		showSearch.h \
		terza.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seconda.o seconda.cpp

terza.o: terza.cpp terza.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terza.o terza.cpp

showSearch.o: showSearch.cpp terza.h \
		showSearch.h \
		app.h \
		ware.h \
		propsw.h \
		software.h \
		hardware.h \
		sharesw.h \
		container.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showSearch.o showSearch.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_form.o: moc_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form.o moc_form.cpp

moc_seconda.o: moc_seconda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seconda.o moc_seconda.cpp

moc_showSearch.o: moc_showSearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_showSearch.o moc_showSearch.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

